/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void delay_ms(uint32_t ms) {
    // Hàm delay, thực hiện đợi trong số miligiây
    // Lưu ý: Cần cấu hình SystemCoreClock cho hệ thống của bạn
    volatile uint32_t i;
    for (i = 0; i < ms * 1000; ++i) {
        __NOP();
    }
}
int main(void)
{

    /* Loop forever */
	for(;;);
}
